experiment:
  name: qalf_vaihingen_irrg_dsm_mobilenetv3_robust_finetune
  output_dir: outputs/qalf_vaihingen_irrg_dsm_mobilenetv3_robust_finetune
  seed: 46

dataset:
  name: vaihingen
  root_dir: data/Vaihingen_prepared_v4
  image_dir: images
  aux_dir: dsm
  mask_dir: masks
  split_dir: splits
  image_suffix: .png
  aux_suffix: .png
  mask_suffix: .png
  num_classes: 6
  input_size: 512
  train_split: train.txt
  val_split: val.txt
  test_split: test.txt
  missing_prob: 0.30
  degradation_prob: 0.35
  normalize_aux: true
  augment: true
  hflip_prob: 0.5
  vflip_prob: 0.5
  rotate90_prob: 0.5
  color_jitter: 0.06

model:
  in_channels_main: 3
  in_channels_aux: 1
  base_channels: 32
  decoder_channels: 128
  num_classes: 6
  dropout: 0.1
  encoder_type: torchvision_mobilenetv3
  encoder_name: mobilenet_v3_large
  encoder_pretrained: true
  aux_encoder_name: mobilenet_v3_large
  aux_encoder_pretrained: true
  freeze_main_encoder: false
  freeze_aux_encoder: false

train:
  device: cuda
  epochs: 28
  batch_size: 8
  num_workers: 4
  optimizer: adamw
  lr: 0.00003
  weight_decay: 0.0001
  grad_clip_norm: 1.0
  distill_start_epoch: 999999
  ema_decay: 0.99
  resume: outputs/qalf_vaihingen_irrg_dsm_mobilenetv3_clean_aug/best_model.pt
  resume_optimizer: false
  early_stopping_patience: 0
  early_stopping_min_delta: 0.0005
  save_best_only: true
  amp: false

loss:
  ce_weight: 1.0
  dice_weight: 0.5
  feat_weight: 0.0
  pred_weight: 0.0
  boundary_weight: 0.0

eval:
  batch_size: 8
  num_workers: 4
